# Generated by Django 5.2.1 on 2025-05-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='رقم الجوال'),
        ),
    ]
